---
# tasks file for win_service_config
- name: 1.0 | Install package
  win_chocolatey:
    name: "{{ package_name }}"
    params: "{{ parameters }}"
    state: latest
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

- name: 2.0 | Start Windows service
  win_service:
    name: "{{ service_name }}"
    state: started
    start_mode: auto
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

- name: 3.0 | Add Windows Firewall rule
  win_firewall_rule:
    name: "{{ service_name }}"
    localport: "{{ local_port }}"
    action: allow
    direction: in
    protocol: "{{ protocol_name }}"
    state: present
    enabled: yes
